import type {Language} from './rules';
export const localeNames={ja:'🇯🇵 日本語',en:'🇺🇸 English',zh:'🇹🇼 繁體中文',ko:'🇰🇷 한국어',th:'🇹🇭 ไทย',id:'🇮🇩 Indonesia',vi:'🇻🇳 Tiếng Việt'};
const ja={title:'新キャラ情報掲示板',home:'トップへ',ranking:'集計表へ',profile:'表示名',register:'表示名を登録してください',save:'保存する',board:'掲示板を開く',back:'新キャラ掲示板に戻る',strength:'強さ',pull:'ガチャ',strong:'強い',normal:'普通',weak:'弱い',yes:'引く',maybe:'迷っている',no:'引かない',newest:'新着順',popular:'いいねが多い順',post:'投稿する',comment:'コメント',reply:'返信',replies:'件の返信',cancelReply:'返信をやめる',replyingTo:'さんに返信',translated:'翻訳文',translating:'翻訳中…',video:'動画付き',media:'写真・動画',mediaPicker:'写真・動画を選ぶ',mediaNote:'写真：JPEG・PNG・WebP・GIF（12MBまで）／動画：MP4・WebM・MOV（200MBまで）',videoUrl:'YouTubeのURL',uploadPreparing:'動画のアップロードを準備中…',uploading:'動画をアップロード中',uploadFinalizing:'動画を保存中…',placeholder:'使ってみた感想や、気になることをどうぞ。',empty:'まだ投稿がありません。最初の感想を書いてみませんか？',likes:'いいねした人を見る',translate:'翻訳',original:'原文',close:'閉じる',owner:'🛡 運営',moderator:'🔧 モデレーター',pin:'📌 運営固定',pinAction:'固定',unpin:'固定解除',hide:'非表示',deleted:'削除',restore:'再表示',archive:'過去の新キャラ掲示板',noBoards:'この月の新キャラはまだ登録されていません。',textOnly:'返信はテキストのみ。URL・画像・動画は投稿できません。',more:'次の投稿',previous:'前の投稿',retry:'もう一度読み込む',unavailable:'現在、掲示板を一時的に読み込めません。',signin:'ChatGPTでログイン',votes:'票',rules:'相手を尊重し、個人情報は書き込まないでください。',saved:'保存しました',readFirst:'見るだけなら表示名の登録は不要です。',translationNote:'翻訳結果は原文を残したまま、この画面に表示します。',translateOpen:'翻訳を開く',evaluation:'非公開・評価用',previewNote:'評価用の投稿です。本番の集計や利用者には影響しません。',admin:'運営・モデレーション',userList:'利用者',hiddenPosts:'非表示の投稿',makeMod:'モデレーターにする',removeMod:'モデレーターを解除',confirm:'実行する',cancel:'キャンセル',confirmAction:'この管理操作を実行しますか？',loading:'読み込み中…',entry:'投票・コメント・写真・動画で、新キャラについて話そう！'};
ja.owner='（運営）';ja.moderator='（モデレーター）';ja.pin='固定';ja.readFirst='ログインは不要です。投稿・反応の前に表示名を決めてください。';ja.evaluation='開発・評価用';
type Labels=typeof ja;
const en:Labels={title:'New character board',home:'Home',ranking:'PvP rankings',profile:'Display name',register:'Choose a display name',save:'Save',board:'Open board',back:'Back to character board',strength:'Is this character strong?',pull:'Will you pull?',strong:'Strong',normal:'Average',weak:'Weak',yes:'Yes',maybe:'Undecided',no:'No',newest:'Newest',popular:'Most liked',post:'Post',comment:'Comment',reply:'Reply',replies:'replies',cancelReply:'Cancel reply',replyingTo:' is being replied to',translated:'Translation',translating:'Translating…',video:'With video',media:'Photo or video',mediaPicker:'Choose photo or video',mediaNote:'Photos: JPEG, PNG, WebP or GIF (up to 12 MB) / Videos: MP4, WebM or MOV (up to 200 MB)',videoUrl:'YouTube URL',uploadPreparing:'Preparing video upload…',uploading:'Uploading video',uploadFinalizing:'Saving video…',placeholder:'Share your experience or ask a question.',empty:'No posts yet. Share the first impression.',likes:'See who liked this',translate:'Translate',original:'Original',close:'Close',owner:'🛡 Owner',moderator:'🔧 Moderator',pin:'📌 Pinned',pinAction:'Pin',unpin:'Unpin',hide:'Hide',deleted:'Delete',restore:'Restore',archive:'Past character boards',noBoards:'No new characters registered for this month.',textOnly:'Text replies only. No URLs, images or videos.',more:'Next posts',previous:'Previous posts',retry:'Try again',unavailable:'The board is temporarily unavailable.',signin:'Sign in with ChatGPT',votes:'votes',rules:'Respect others. Do not post personal information.',saved:'Saved',readFirst:'No login is needed. Choose a display name before posting or reacting.',translationNote:'Translations appear here while preserving the original text.',translateOpen:'Open translation',evaluation:'Development review',previewNote:'Review posts do not affect production statistics or visitors.',admin:'Moderation',userList:'Users',hiddenPosts:'Hidden posts',makeMod:'Make moderator',removeMod:'Remove moderator',confirm:'Confirm',cancel:'Cancel',confirmAction:'Apply this moderation action?',loading:'Loading…',entry:'Talk about new characters with votes, comments, photos and videos.'};
const overrides:Partial<Record<Language,Partial<Labels>>>={
 zh:{title:'新角色討論區',home:'首頁',ranking:'PvP排行榜',profile:'顯示名稱',register:'請設定顯示名稱',save:'儲存',board:'開啟討論區',back:'返回角色討論區',strength:'這個角色強嗎？',pull:'你會抽嗎？',strong:'強',normal:'普通',weak:'弱',yes:'會抽',maybe:'猶豫中',no:'不抽',newest:'最新',popular:'最多讚',post:'發布',comment:'留言',video:'附影片',videoUrl:'YouTube網址',placeholder:'分享使用心得或提出問題。',empty:'還沒有留言，來分享第一個心得吧。',likes:'查看按讚的人',translate:'翻譯',original:'原文',close:'關閉',owner:'🛡 管理員',moderator:'🔧 版主',pin:'📌 置頂',archive:'過去的角色討論區',textOnly:'只能回覆文字，不可附網址、圖片或影片。',votes:'票',entry:'透過投票、留言和影片討論新角色。'},
 ko:{title:'신규 캐릭터 게시판',home:'홈',ranking:'PvP 순위',profile:'표시 이름',register:'표시 이름을 등록하세요',save:'저장',board:'게시판 열기',back:'캐릭터 게시판으로',strength:'이 캐릭터, 강한가요?',pull:'뽑을 건가요?',strong:'강함',normal:'보통',weak:'약함',yes:'뽑는다',maybe:'고민 중',no:'안 뽑는다',newest:'최신순',popular:'좋아요순',post:'게시',comment:'댓글',video:'동영상 첨부',videoUrl:'YouTube URL',placeholder:'사용 후기나 궁금한 점을 남겨 주세요.',empty:'첫 번째 댓글을 남겨 보세요.',likes:'좋아요한 사람',translate:'번역',original:'원문',close:'닫기',owner:'🛡 운영자',moderator:'🔧 관리자',pin:'📌 고정',archive:'지난 캐릭터 게시판',textOnly:'텍스트만 가능합니다. URL, 이미지, 동영상은 불가합니다.',votes:'표',entry:'투표, 댓글, 동영상으로 신규 캐릭터를 이야기해요.'},
 th:{title:'กระดานตัวละครใหม่',home:'หน้าหลัก',ranking:'อันดับ PvP',profile:'ชื่อที่แสดง',save:'บันทึก',board:'เปิดกระดาน',strength:'ตัวละครนี้เก่งไหม?',pull:'จะสุ่มไหม?',strong:'เก่ง',normal:'ปกติ',weak:'อ่อน',yes:'สุ่ม',maybe:'ยังไม่แน่ใจ',no:'ไม่สุ่ม',newest:'ล่าสุด',popular:'ถูกใจมากที่สุด',post:'โพสต์',comment:'ความคิดเห็น',video:'แนบวิดีโอ',translate:'แปล',original:'ต้นฉบับ',close:'ปิด',votes:'โหวต'},
 id:{title:'Forum karakter baru',home:'Beranda',ranking:'Peringkat PvP',profile:'Nama tampilan',save:'Simpan',board:'Buka forum',strength:'Apakah karakter ini kuat?',pull:'Akan melakukan gacha?',strong:'Kuat',normal:'Biasa',weak:'Lemah',yes:'Ya',maybe:'Masih ragu',no:'Tidak',newest:'Terbaru',popular:'Paling disukai',post:'Kirim',comment:'Komentar',video:'Dengan video',translate:'Terjemahkan',original:'Asli',close:'Tutup',votes:'suara'},
 vi:{title:'Diễn đàn nhân vật mới',home:'Trang chủ',ranking:'Xếp hạng PvP',profile:'Tên hiển thị',save:'Lưu',board:'Mở diễn đàn',strength:'Nhân vật này mạnh không?',pull:'Bạn sẽ quay gacha chứ?',strong:'Mạnh',normal:'Bình thường',weak:'Yếu',yes:'Có',maybe:'Đang phân vân',no:'Không',newest:'Mới nhất',popular:'Nhiều lượt thích',post:'Đăng',comment:'Bình luận',video:'Kèm video',translate:'Dịch',original:'Bản gốc',close:'Đóng',votes:'phiếu'}
};
export function labels(lang:Language):Labels{return lang==='ja'?ja:{...en,...overrides[lang]};}
export function errorText(code:string,lang:Language){const errors:Record<string,string>={rate_limited:'操作が続いています。少し待ってからお試しください。',profile_required:'先に表示名を保存してください。',invalid_text:'空欄や文字数を確認してください。名前は30文字、本文は2,000文字までです。',invalid_video:'YouTubeの動画URLを入力してください。',invalid_media:'動画は200MB、写真は12MBまでです。形式も確認してください。選んだ内容は残しています。',upload_incomplete:'動画の一部が届いていません。通信を確認して、もう一度お試しください。',upload_busy:'同じ動画のアップロードが進行中です。少し待ってからお試しください。',upload_expired:'動画のアップロード期限が切れました。もう一度ファイルを選んでください。',translation_unavailable:'翻訳を読み込めませんでした。原文はそのまま表示されています。',feature_disabled:'この機能は現在一時停止しています。ほかの機能は利用できます。',read_only:'現在メンテナンス中のため、新規投稿・反応・投票は一時停止しています。閲覧は通常通り利用できます。',archive_readonly:'過去月は閲覧専用です。新しい投稿や投票は当月の掲示板で行ってください。',text_only:'返信はテキストだけです。URL・画像・動画は投稿できません。',duplicate_post:'同じ内容が直前に投稿されています。',forbidden:'この操作の権限がありません。',not_found:'投稿が見つからないか、非表示になっています。'};return lang==='ja'?(errors[code]||'処理できませんでした。内容は残しています。時間をおいて再度お試しください。'):`Unable to complete (${code}). Your draft is preserved. Please check the input or try again later.`;}
