import { sqliteTable,text,integer,primaryKey,index,uniqueIndex } from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{id:text('id').primaryKey(),subject:text('subject').notNull().unique(),name:text('name').notNull(),displayNameSet:integer('display_name_set').notNull().default(0),role:text('role').notNull().default('user'),created:integer('created').notNull()},t=>[index('users_display_name_set').on(t.displayNameSet,t.created)]);
export const boards=sqliteTable('boards',{id:text('id').primaryKey(),month:text('month').notNull(),character:text('character').notNull(),name:text('name').notNull(),image:text('image').notNull()},t=>[uniqueIndex('board_character_month').on(t.month,t.character)]);
export const posts=sqliteTable('posts',{id:text('id').primaryKey(),board:text('board').notNull().references(()=>boards.id),author:text('author').notNull().references(()=>users.id),parent:text('parent'),body:text('body').notNull(),video:text('video'),mediaKey:text('media_key'),mediaType:text('media_type'),mediaName:text('media_name'),mediaSize:integer('media_size'),mediaGroup:text('media_group'),status:text('status').notNull().default('visible'),pinned:integer('pinned').notNull().default(0),created:integer('created').notNull(),request:text('request').notNull()},t=>[index('posts_board_parent').on(t.board,t.parent,t.status,t.created),index('posts_parent_status_created').on(t.parent,t.status,t.created),index('posts_board_status_created').on(t.board,t.status,t.created),index('posts_media_group').on(t.mediaGroup,t.created),uniqueIndex('posts_author_request').on(t.author,t.request)]);
export const likes=sqliteTable('likes',{post:text('post').notNull().references(()=>posts.id),user:text('user').notNull().references(()=>users.id),created:integer('created').notNull()},t=>[primaryKey({columns:[t.post,t.user]})]);
export const votes=sqliteTable('votes',{board:text('board').notNull().references(()=>boards.id),user:text('user').notNull().references(()=>users.id),poll:text('poll').notNull(),choice:integer('choice').notNull()},t=>[primaryKey({columns:[t.board,t.user,t.poll]})]);
export const limits=sqliteTable('limits',{key:text('key').primaryKey(),count:integer('count').notNull(),until:integer('until').notNull()});
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),target:text('target').notNull(),created:integer('created').notNull()});
export const translations=sqliteTable('translations',{post:text('post').notNull(),language:text('language').notNull(),body:text('body').notNull()},t=>[primaryKey({columns:[t.post,t.language]})]);
export const helpful=sqliteTable('helpful',{post:text('post').notNull().references(()=>posts.id),user:text('user').notNull().references(()=>users.id),created:integer('created').notNull()},t=>[primaryKey({columns:[t.post,t.user]})]);
export const visits=sqliteTable('visits',{subject:text('subject').primaryKey(),seen:integer('seen').notNull()});
export const uploadSessions=sqliteTable('upload_sessions',{id:text('id').primaryKey(),user:text('user').notNull().references(()=>users.id),board:text('board').notNull().references(()=>boards.id),body:text('body').notNull(),request:text('request').notNull(),mediaKey:text('media_key').notNull(),mediaType:text('media_type').notNull(),mediaName:text('media_name').notNull(),mediaSize:integer('media_size').notNull(),mediaGroup:text('media_group'),uploadId:text('upload_id').notNull(),partSize:integer('part_size').notNull(),status:text('status').notNull().default('uploading'),post:text('post'),created:integer('created').notNull(),updated:integer('updated').notNull()},t=>[uniqueIndex('upload_sessions_user_request').on(t.user,t.request),index('upload_sessions_user_status').on(t.user,t.status,t.updated),index('upload_sessions_media_group').on(t.mediaGroup,t.created)]);
export const uploadParts=sqliteTable('upload_parts',{session:text('session').notNull().references(()=>uploadSessions.id),partNumber:integer('part_number').notNull(),etag:text('etag').notNull(),size:integer('size').notNull(),created:integer('created').notNull()},t=>[primaryKey({columns:[t.session,t.partNumber]})]);
// Additive operational switches. Empty means the safe defaults in
// community-features.ts, so deployment cannot disable an existing feature.
export const featureFlags=sqliteTable('feature_flags',{name:text('name').primaryKey(),enabled:integer('enabled').notNull().default(1),updated:integer('updated').notNull(),actor:text('actor').references(()=>users.id)});
// Contribution labels are intentionally separate from role permissions. A
// badge can never grant moderation authority; only users.role is authoritative.
export const userBadges=sqliteTable('user_badges',{user:text('user').notNull().references(()=>users.id),badge:text('badge').notNull(),grantedBy:text('granted_by').notNull().references(()=>users.id),created:integer('created').notNull()},t=>[primaryKey({columns:[t.user,t.badge]}),index('user_badges_user').on(t.user)]);
// One report per viewer and post. Reports keep moderation work separate from
// the public list and never duplicate the post body or media bytes.
export const postReports=sqliteTable('post_reports',{post:text('post').notNull().references(()=>posts.id),reporter:text('reporter').notNull().references(()=>users.id),created:integer('created').notNull()},t=>[primaryKey({columns:[t.post,t.reporter]}),index('post_reports_created').on(t.created)]);
